export enum ACTION_TYPE {
    AUTH= "AUTH",
    SET_LOADING= "SET_LOADING",
    GET_ALL_ARTICLE="GET_ALL_ARTICLE",
    CREATE_ARTICLE="CREATE_ARTICLE",
    UPDATE_ARTICLE= "UPDATE_ARTICLE",
    DELETE_ARTICLE="DELETE_ARTICLE"
}